server:
  port: 8080

cache:
  ttl: "1h"  # Cache time-to-live (e.g., "30m", "1h", "24h")
  folder: "./cache"  # Cache storage directory

rules:
  mode: "whitelist"  # "whitelist" or "blacklist"
  rules:
    - base_uri: "https://api.github.com"
      methods: ["GET"]
    - base_uri: "https://httpbin.org"
      methods: ["GET", "POST"]
    - base_uri: "http://example.com"
      methods: ["GET"]
