server:
  port: 8080
  ssl_bumping:
    enabled: true  # Set to true to enable SSL bumping
    cert_file: "./ssl/server.crt"  # Server certificate for SSL bumping
    key_file: "./ssl/ca.key"   # Server private key for SSL bumping
    ca_file: "./ssl/ca.crt"        # CA certificate for generating dynamic certs

cache:
  ttl: "1h"  # Cache time-to-live (e.g., "30m", "1h", "24h")
  folder: "./cache"  # Cache storage directory

log:
  level: "debug"  # Log level: "debug", "info", "warn", "error"

rules:
  mode: "blacklist"  # "whitelist" or "blacklist"
  rules: []  # No rules means cache everything in blacklist mode

# By default, the rules are a blacklist with no rules.
# Example of a whitelist configuration:
# rules:
  # mode: "whitelist"  # "whitelist" or "blacklist"
  # rules:
  #   - base_uri: "https://api.github.com"
  #     methods: ["GET"]
  #   - base_uri: "https://httpbin.org"
  #     methods: ["GET", "POST"]
  #   - base_uri: "http://example.com"
  #     methods: ["GET"]
