server:
  address: ":8080" # port for transparent HTTP proxying, as well and HTTP/HTTPS classic proxying
  tls:
    enabled: true  # Set to true to enable TLS interception
    ca_key_file: "./local/ca.key"   # CA private key to generate dynamic certs
    ca_cert_file: "./local/ca.crt"  # CA certificate
    address: ":8443"  # Address for transparent HTTPS proxying

cache:
  ttl: "1h"  # Cache time-to-live (e.g., "30m", "1h", "24h")
  folder: "./cache"  # Cache storage directory

log:
  level: "debug"
  third_party: true  # Enable logging of third-party libraries

rules:
  mode: "blacklist"  # "whitelist" or "blacklist"
  rules: []  # No rules means cache everything in blacklist mode

# By default, the rules are a blacklist with no rules.
# Example of a whitelist configuration:
# rules:
  # mode: "whitelist"  # "whitelist" or "blacklist"
  # rules:
  #   - base_uri: "https://api.github.com"
  #     methods: ["GET"]
  #   - base_uri: "https://httpbin.org"
  #     methods: ["GET", "POST"]
  #   - base_uri: "http://example.com"
  #     methods: ["GET"]
