name: Go

on:
  push:
    branches: ["main", "ci"]
    tags: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.5"

      - name: Install pre-commit deps
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Install Just
        run: go install github.com/casey/just@latest

      - name: Build
        run: just build

      - name: Test
        run: just test

      - name: Make coverage report
        run: go test -coverprofile=coverage.out ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
